import React from "react";
import jsPDF from "jspdf";
import "./ReportExport.css";

const ReportExport = ({ data }) => {
  const handleExport = () => {
    const doc = new jsPDF();
    doc.setFont("helvetica");
    doc.setFontSize(18);
    doc.setTextColor("#f97316");
    doc.text("Uranium Simulation Report", 20, 20);

    doc.setFontSize(12);
    doc.setTextColor("#333");
    doc.text(`Blasting Intensity: ${data.blasting}`, 20, 40);
    doc.text(`Environmental Protection: ${data.protection}`, 20, 50);
    doc.text(`Impact Rating: ${data.impact}`, 20, 60);

    doc.setFontSize(10);
    doc.setTextColor("#888");
    doc.text("Generated by U3O8Flow Simulator", 20, 80);
    doc.save("U3O8Flow_Report.pdf");
  };

  return (
    <div className="report-wrapper">
      <button className="report-button" onClick={handleExport}>
        📄 Download Report (PDF)
      </button>
    </div>
  );
};

export default ReportExport;
